### ISSUE TITLE
Can't build from source, missing https:// in about.html and broken page link

### ISSUE THREAD

**Issue by samuelbeepdev** [Ensomniacs/seasonoftheplague#1]
about.html:164, "https://" needed before link to Protheon Twitter.
about.html:464, specialthanks.html not found, workaround is to remove link.

With these changes, parcel builds correctly.

**Comment by Ensomniacs** [comment]
Specialthanks.html was not yet active and has now been implemented as of 8:35pm CST last night. :D
"https;//" added to protheon's link will be pushed with gallery modifications.

Thank you!
